_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_split1_30shot/combined/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    FREEZE_FEAT: False
  BACKBONE:
    FREEZE: False
  PROPOSAL_GENERATOR:
    FREEZE: False
SOLVER:
  BASE_LR: 0.008
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_ITERS: 0